on: push
name: Verify the module
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: |
        npm install -g npm@8.1.4
        npm ci

    - name: Run npm verify_all
      run: npm run verify_all
